version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: tender-test-app-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: tender-test-app-php
    volumes:
      - ./src:/var/www/html
  db:
    image: postgres:latest
    container_name: tender-test-app-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"